/* -----------------------------------------------------------------------
/
/  proclist.c
/
/  Copyright (c) 1990,  EG&G Instruments Inc.
/
/  $Header:   J:/logfiles/oma4000/macro/proclist.c_v   0.24   06 Jul 1992 12:52:18   maynard  $
/  $Log:   J:/logfiles/oma4000/macro/proclist.c_v  $
 *
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "handy.h"
#include "macruntm.h"
#include "macsymbl.h"   // VERLEN
#include "crvheadr.h"   // SHORTTYPE

/* macro file will show:  null ended id string of FTIDLEN bytes */
/*                        version number string of VERLEN bytes */
/*                        number of symbols                     */
/*                        DECLARATION array                     */

/* also in filestuf.c */
const CHAR *fidMacroOMA4 = "MACRO EG&G PARC OMA4";

const CHAR Version[VERLEN] = "2.04";

// MUST MATCH UP EXACTLY with the CommandList[] function pointer table
// defined in macrores.c

enum CommandListIndex {

  INDX_PLUS = 0,         
  INDX_MINUS,            
  INDX_MULTIPLY,         
  INDX_DIVIDE,           
  INDX_INTDIV,           
  INDX_MOD,              
  INDX_TRUNC,            
  INDX_ROUND,            
  INDX_ABS,              
  INDX_AND,              
  INDX_OR,               
  INDX_XOR,              
  INDX_NOT,              
  INDX_SHL,              
  INDX_SHR,              
  INDX_LOG,              
  INDX_LN,               
  INDX_EXP,              
  INDX_SIN,              
  INDX_COS,              
  INDX_TAN,              
  INDX_ATAN,             
  INDX_ASIN,             
  INDX_ACOS,             
  INDX_ATAN2,            
  INDX_G_MAX,            
  INDX_S_MAX,            
  INDX_G_MIN,            
  INDX_S_MIN,            
  INDX_STRLEN,           
  INDX_RATFIT,           
  INDX_POLYFIT,          
  INDX_POLYDERV,         
  INDX_SMOOTH,           
  INDX_AVG_STD_DEV,      
  INDX_ABSORB,      
  INDX_ASSIGN_TO,        
  INDX_EQUALTO,          
  INDX_NOTEQUALTO,       
  INDX_LESSTHAN,         
  INDX_GREATERTHAN,      
  INDX_LESSTHANEQ,       
  INDX_GREATERTHANEQ,    
  INDX_ASSIGN,           
  INDX_CLOSE,            
  INDX_RESET,            
  INDX_REWRITE,          
  INDX_SEEK,             
  INDX_MACREADCH,        
  INDX_READ,             
  INDX_READLN,           
  INDX_WRITE,            
  INDX_WRITELN,          
  INDX_EOLN,             
  INDX_EOF,              
  INDX_KEYPRESSED,       
  INDX_G_MEM,            
  INDX_G_MEMW,           
  INDX_S_MEM,            
  INDX_S_MEMW,           
  INDX_G_PORT,           
  INDX_G_PORTW,          
  INDX_S_PORT,           
  INDX_S_PORTW,          
  INDX_D_NUMBYTES,       
  INDX_D_NUMPTS,         
  INDX_D_ADD_MEM,        
  INDX_DG_ADP,           
  INDX_D_AREA,           
  INDX_D_READ_MEM,       
  INDX_D_LOAD_MEM,       
  INDX_D_CAREA,          
  INDX_D_CL,             
  INDX_D_CLR,            
  INDX_D_CLR_ALL,        
  INDX_D_CRM,            
  INDX_DG_DA,            
  INDX_DS_DA,            
  INDX_D_LOAD_DAD,       
  INDX_DG_DM,            
  INDX_DG_DT,            
  INDX_DS_DT,            
  INDX_DG_ERR,           
  INDX_DG_ET,            
  INDX_DS_ET,            
  INDX_DG_FREQ,          
  INDX_DS_FREQ,          
  INDX_DG_I,             
  INDX_DS_I,             
  INDX_DG_ID,            
  INDX_DG_J,             
  INDX_DS_J,             
  INDX_DG_K,             
  INDX_DS_K,             
  INDX_DG_L,             
  INDX_DS_L,             
  INDX_D_STORE_DAD,      
  INDX_DG_MAX_MEM,       
  INDX_DG_MEM,           
  INDX_DS_MEM,           
  INDX_DG_MIN_ET,
  INDX_DG_PTIME,
  INDX_DS_PTIME,
  INDX_DG_STIME,
  INDX_DS_STIME,
  INDX_DG_FTIME,
  INDX_DG_PD,            
  INDX_DS_PD,            
  INDX_DG_PLSR,          
  INDX_DG_PW,            
  INDX_DS_PW,            
  INDX_D_RUN,            
  INDX_D_STOP,           
  INDX_DG_SAME_ET,       
  INDX_DS_SAME_ET,       
  INDX_DS_SHUTTER,       
  INDX_D_SUB,            
  INDX_DG_SYNC,          
  INDX_DS_SYNC,          
  INDX_DG_VER,           
  INDX_DG_ACTIVEX,       
  INDX_DS_ACTIVEX,       
  INDX_DG_ACTIVEY,       
  INDX_DS_ACTIVEY,       
  INDX_DG_DELTAX,        
  INDX_DS_DELTAX,        
  INDX_DG_DELTAY,        
  INDX_DS_DELTAY,        
  INDX_DG_OUTPUT_REG,    
  INDX_DS_OUTPUT_REG,    
  INDX_DG_H,             
  INDX_DS_H,             
  INDX_DG_ANTI_BLOOM,    
  INDX_DS_ANTI_BLOOM,    
  INDX_DG_SCANMODE,      
  INDX_DS_SCANMODE,      
  INDX_DG_SHUTMODE,      
  INDX_DS_SHUTMODE,      
  INDX_DG_SCITC,         
  INDX_DS_SCITC,         
  INDX_DG_SCMP,          
  INDX_DG_SLCMODE,       
  INDX_DS_SLCMODE,       
  INDX_DG_POINT,         
  INDX_DS_POINT,         
  INDX_DG_POINTS,        
  INDX_DS_POINTS,        
  INDX_DG_REGIONS,
  INDX_DS_REGIONS,
  INDX_DG_REGION,
  INDX_DS_REGION,
  INDX_DG_REGSIZE,
  INDX_DS_REGSIZE,
  INDX_DG_REGET,
  INDX_DS_REGET,
  INDX_DG_TRACK,         
  INDX_DS_TRACK,         
  INDX_DG_TRACKS,        
  INDX_DS_TRACKS,        
  INDX_DG_TRKMODE,       
  INDX_DS_TRKMODE,       
  INDX_DG_WFTC,          
  INDX_DS_WFTC,          
  INDX_DG_WFTO,          
  INDX_DS_WFTO,          
  INDX_DG_X0,            
  INDX_DS_X0,            
  INDX_DG_Y0,            
  INDX_DS_Y0,

  INDX_DGOUTPIA,
  INDX_DSOUTPIA,
  
  INDX_DGINPIA,
  
  INDX_DGPAUDIO,
  INDX_DSPAUDIO,
  
  INDX_DGPTRIGNUM,
  INDX_DSPTRIGNUM,
  
  INDX_DGPTRIGSRC,
  INDX_DSPTRIGSRC,
  
  INDX_DGPTRIGTRSH,
  INDX_DSPTRIGTRSH,
  
  INDX_DGPDELINC,
  INDX_DSPDELINC,
  
  INDX_DGPDELRANGE,
  INDX_DSPDELRANGE,
  
  INDX_DGPIMODE,
  INDX_DSPIMODE,

  INDX_DGSTREAKMODE,
  INDX_DSSTREAKMODE,

  INDX_DGEXPOSEDROWS,
  INDX_DSEXPOSEDROWS,

  INDX_DGPRETRIGTRACKS,
  INDX_DSPRETRIGTRACKS,

  INDX_CREATE_CURVE,     
  INDX_CS_COUNT,         
  INDX_DC_COUNT,         
  INDX_MC_COUNT,         
  INDX_LOAD_METHOD,      
  INDX_SAVE_METHOD,      
  INDX_LOAD_FILE_CURVES, 
  INDX_SAVE_FILE_CURVES, 
  INDX_INS_CURVE,        
  INDX_INS_CURVE_SET,    
  INDX_DEL_CURVE_SET,    
  INDX_DEL_CURVE,        
  INDX_CREATE_CURVE_SET, 
  INDX_G_CURVE_SET_INDEX,
  INDX_G_ACTIVE_WINDOW,  
  INDX_S_ACTIVE_WINDOW,  
  INDX_PLOT_WINDOW,      
  INDX_S_PLOT_STYLE,     
  INDX_S_WINDOW_STYLE,   
  INDX_S_ACCUM,          
  INDX_S_LIVE,           
  INDX_S_FRAME_CAPTURE,  
  INDX_LOAD_BACKGROUND,  
  INDX_CHANGE_CURVE_SIZE,
  INDX_RUN_MACRO_FILE,   
  INDX_GPIB_CLEAR,       
  INDX_GPIB_SEND,        
  INDX_GPIB_RESPONSE,    
  INDX_GPIB_SERIAL_POLL, 
  INDX_G_DET_ADDRESS,    
  INDX_S_DET_ADDRESS,    
  INDX_G_DET_INDEX,      
  INDX_S_DET_INDEX,      
  INDX_START_FRESH,      
  INDX_DROP,             
  INDX_CSCURVE,          
  INDX_DCCURVE,          
  INDX_MCCURVE,          
  INDX_MENU_REF,         
  INDX_FORM_REF,         
  INDX_FIELD_REF,        
  INDX_LEAVE_FORM,       
  INDX_LEAVE_MENU,       
  INDX_FOCUS_FIELD,      
  INDX_ENTER_GRAPH,      
  INDX_LEAVE_GRAPH,      
  INDX_HELP,             
  INDX_GO_LIVE,          
  INDX_STOP_LIVE,        
  INDX_ZOOM,             
  INDX_RESTORE_ZOOM,     
  INDX_AUTO_SCALE,       
  INDX_SCALEX,       
  INDX_SCALEY,       
  INDX_SCALEZ,       
  INDX_SELECT_WINDOW,    
  INDX_SET_THRESHOLD,    
  INDX_DRAW_PEAKS,       
  INDX_ADD_KNOT,         
  INDX_REPLOT_WINDOW,    
  INDX_REPLOT_SCREEN,    
  INDX_MOVE_CURSOR,

  INDX_EXPAND_X,
  INDX_EXPAND_Y,
  INDX_CONTRACT_X,
  INDX_CONTRACT_Y,

  INDX_G_ACTIVE_PLOT,    
  INDX_S_ACTIVE_PLOT,    
  INDX_EXPAND_TAGGED,    
  INDX_RESTORE_EXPAND,   
  INDX_TAG_CURVE,        
  INDX_UNTAG_CURVE,      
  INDX_DG_COOL,          
  INDX_DS_COOL,          
  INDX_DG_ACTIVE,

  INDX_SPEC_CMD,
  INDX_SPEC_GETS,
  INDX_SPEC_RESET,
  INDX_SPEC_SELECT,
  INDX_SPEC_OFFSET,
  INDX_SPEC_GO,
  INDX_SPEC_WLEN,
  INDX_SPEC_GRATING,
  INDX_SPEC_STORE,
  INDX_SPEC_S_DISP,

  INDX_DOSCMD,
  INDX_STOF,
  INDX_FTOS,
  INDX_GCMD_PROMPT,
  INDX_SCMD_PROMPT,

  INDX_LOADLAMPFILE,
  INDX_SAVELAMPFILE,
  INDX_ADDYCALIBPAIR,
  INDX_DELYCALIBPAIR,
  INDX_DELETELAMPDATA,
  INDX_GENCORREXSET,

  INDX_SETFILTER,
  INDX_MACWAIT,

  INDX_MACCOMINIT,
  INDX_MACCOMSTAT,
  INDX_MACCOMOUT,
  INDX_MACCOMIN,

  INDX_MACRDMOUSE,

  INDX_MACPAUSEL,
  INDX_MACFREERL,

  INDX_SYSTIME,
  INDX_GETCAL,
  INDX_SETCAL,

  INDX_G_PLOT_STYLE,
  };

DECLARATION PreDefSymbols[] = {

{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_NONE,
   "BUFLEN", 0, (int) 80 },

{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "INTEGER", 0, (int) TYPE_INTEGER },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "WORD", 0, (int) TYPE_WORD },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "LONG_INTEGER", 0, (int) TYPE_LONG_INTEGER },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "SINGLE", 0, (int) TYPE_REAL4 },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "REAL", 0, (int) TYPE_REAL },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "BYTE", 0, (int) TYPE_BYTE },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "BOOLEAN", 0, (int) TYPE_BOOLEAN },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "STRING", 0, (int) TYPE_STRING },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,                // 10
   "FILE", 0, (int) TYPE_FILE },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "TEXT", 0, (int) TYPE_TEXTFILE },

{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "START_INDEX", 0, (int) CURVE_START_INDEX },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "COUNT", 0, (int) CURVE_COUNT },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "NAME", 0, (int) CURVE_NAME },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "PATH", 0, (int) CURVE_PATH },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "DESC", 0, (int) CURVE_DESC },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "DISPLAY", 0, (int) CURVE_DISPLAY },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "POINT_COUNT", 0, (int) CURVE_POINT_COUNT },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "TIME", 0, (int) CURVE_TIME },
{ CLASS_SCALAR, TYPE_LONG_INTEGER, SYMATTR_CONSTANT,           // 20
   "SRC_COMP", 0, (int) CURVE_SCMP },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "FRAME", 0, (int) CURVE_FRAME },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "TRACK", 0, (int) CURVE_TRACK },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "MIN", 0, (int) CURVE_YMIN },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "MAX", 0, (int) CURVE_YMAX },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "XMIN", 0, (int) CURVE_XMIN },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "XMAX", 0, (int) CURVE_XMAX },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "XUNITS", 0, (int) CURVE_XUNITS },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "YUNITS", 0, (int) CURVE_YUNITS },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,
   "X", 0, (int) CURVE_POINTX },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT,                // 30
   "Y", 0, (int) CURVE_POINTY },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   ":=", 0, { 2, INDX_ASSIGN_TO, INVALID_INDEX} },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "=", 0, { 2, INDX_EQUALTO, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "<>", 0, { 2, INDX_NOTEQUALTO, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "<", 0, { 2, INDX_LESSTHAN, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   ">", 0, { 2, INDX_GREATERTHAN, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "<=", 0, { 2, INDX_LESSTHANEQ, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   ">=", 0, { 2, INDX_GREATERTHANEQ, INVALID_INDEX} },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "+", 0, { 2, INDX_PLUS, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "-", 0, { 2, INDX_MINUS, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,     // 40
   "*", 0, { 2, INDX_MULTIPLY, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "/", 0, { 2, INDX_DIVIDE, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DIV", 0, { 2, INDX_INTDIV, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "MOD", 0, { 2, INDX_MOD, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "TRUNC", 0, { 1, INDX_TRUNC, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "ROUND", 0, { 1, INDX_ROUND, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "ABS", 0, { 1, INDX_ABS, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "AND", 0, { 2, INDX_AND, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "OR", 0, { 2, INDX_OR, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "XOR", 0, { 2, INDX_XOR, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,     // 50
   "NOT", 0, { 1, INDX_NOT, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "SHL", 0, { 1, INDX_SHL, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "SHR", 0, { 1, INDX_SHR, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "LOG", 0, { 1, INDX_LOG, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "LN", 0, { 1, INDX_LN, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "EXP", 0, { 2, INDX_EXP, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "SIN", 0, { 1, INDX_SIN, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "COS", 0, { 1, INDX_COS, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "TAN", 0, { 1, INDX_TAN, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "ATAN", 0, { 1, INDX_ATAN, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,     // 60
   "ASIN", 0, { 1, INDX_ASIN, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "ACOS", 0, { 1, INDX_ACOS, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "ATAN2", 0, { 2, INDX_ATAN2, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "AVG_STD_DEV", 0, { 6, INDX_AVG_STD_DEV, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "ABSORB", 0, { 2, INDX_ABSORB, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "SMOOTH", 0, { 3, INDX_SMOOTH, INVALID_INDEX} },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DROP", 0, { 1, INDX_DROP, INVALID_INDEX} },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "ASSIGN", 0, { 2, INDX_ASSIGN, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "CLOSE", 0, { 1, INDX_CLOSE, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "READCH", 0, { 0, INDX_MACREADCH, INVALID_INDEX} },

{ CLASS_EXECUTABLE,
  TYPE_PROCEDURE,
  SYMATTR_NONE,
  "READ",
  0,
  { 0, INDX_READ, INVALID_INDEX}
},
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "READLN", 0, { 0, INDX_READLN, INVALID_INDEX}},
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "WRITE", 0, { 0, INDX_WRITE, INVALID_INDEX} },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,                 // 70
   "WRITELN", 0, { 0, INDX_WRITELN, INVALID_INDEX} },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "RESET", 0, { 1, INDX_RESET, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "REWRITE", 0, { 1, INDX_REWRITE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "SEEK", 0, { 2, INDX_SEEK, INVALID_INDEX } },

{ CLASS_EXECUTABLE,
  TYPE_PROCEDURE,
  SYMATTR_RETURNS_VALUE,
  "EOLN",
  0,
  { 1, INDX_EOLN, INVALID_INDEX }
},
{ CLASS_EXECUTABLE,
  TYPE_PROCEDURE,
  SYMATTR_RETURNS_VALUE,
  "EOF",
  0,
  { 1, INDX_EOF, INVALID_INDEX }
},
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "KEYPRESSED", 0, { 0, INDX_KEYPRESSED, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "CS", 0, { 0, INDX_CSCURVE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DC", 0, { 0, INDX_DCCURVE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "MC", 0, { 0, INDX_MCCURVE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,        // 80
   "G_MAX", 0, { 0, INDX_G_MAX, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "S_MAX", 0, { 1, INDX_S_MAX, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "G_MIN", 0, { 0, INDX_G_MIN, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "S_MIN", 0, { 1, INDX_S_MIN, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "STRLEN", 0, { 1, INDX_STRLEN, INVALID_INDEX } },


{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "CS_COUNT", 0, { 0, INDX_CS_COUNT, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DC_COUNT", 0, { 0, INDX_DC_COUNT, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "MC_COUNT", 0, { 0, INDX_MC_COUNT, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "LOAD_METHOD", 0, { 1, INDX_LOAD_METHOD, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "SAVE_METHOD", 0, { 1, INDX_SAVE_METHOD, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "LOAD_FILE_CURVES", 0, { 6, INDX_LOAD_FILE_CURVES, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,                 // 90
   "SAVE_FILE_CURVES", 0, { 6, INDX_SAVE_FILE_CURVES, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "INS_CURVE", 0, { 2, INDX_INS_CURVE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "INS_CURVE_SET", 0, { 6, INDX_INS_CURVE_SET, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DEL_CURVE_SET", 0, { 1, INDX_DEL_CURVE_SET, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DEL_CURVE", 0, { 1, INDX_DEL_CURVE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "CREATE_CURVE_SET", 0, { 4, INDX_CREATE_CURVE_SET, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "G_CURVE_SET_INDEX", 0, { 3, INDX_G_CURVE_SET_INDEX, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "G_ACTIVE_WINDOW", 0, { 0, INDX_G_ACTIVE_WINDOW, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "S_ACTIVE_WINDOW", 0, { 1, INDX_S_ACTIVE_WINDOW, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "PLOT_WINDOW", 0, { 2, INDX_PLOT_WINDOW, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,                    // 100
   "S_PLOT_STYLE", 0, { 20, INDX_S_PLOT_STYLE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "S_WINDOW_STYLE", 0, { 1, INDX_S_WINDOW_STYLE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "S_ACCUM", 0, { 1, INDX_S_ACCUM, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "S_LIVE", 0, { 1, INDX_S_LIVE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "S_FRAME_CAPTURE", 0, { 1, INDX_S_FRAME_CAPTURE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "LOAD_BACKGROUND", 0, { 2, INDX_LOAD_BACKGROUND, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "CHANGE_CURVE_SIZE", 0, { 4, INDX_CHANGE_CURVE_SIZE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "RUN_MACRO_FILE", 0, { 1, INDX_RUN_MACRO_FILE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "RUN", 0, { 1, INDX_RUN_MACRO_FILE, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "GPIB_CLEAR", 0, { 0, INDX_GPIB_CLEAR, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,       // 110
   "GPIB_SEND", 0, { 2, INDX_GPIB_SEND, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "GPIB_RESPONSE", 0, { 2, INDX_GPIB_RESPONSE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "GPIB_SERIAL_POLL", 0, { 1, INDX_GPIB_SERIAL_POLL, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "G_DET_ADDRESS", 0, { 0, INDX_G_DET_ADDRESS, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "S_DET_ADDRESS", 0, { 1, INDX_S_DET_ADDRESS, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "G_DET_INDEX", 0, { 0, INDX_G_DET_INDEX, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "S_DET_INDEX", 0, { 1, INDX_S_DET_INDEX, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "START_FRESH", 0, { 0, INDX_START_FRESH, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "G_MEM", 0, { 1, INDX_G_MEM, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "G_MEMW", 0, { 1, INDX_G_MEMW, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,              // 120
   "S_MEM", 0, { 2, INDX_S_MEM, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "S_MEMW", 0, { 2, INDX_S_MEMW, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "G_PORT", 0, { 1, INDX_G_PORT, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "G_PORTW", 0, { 1, INDX_G_PORTW, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "S_PORT", 0, { 2, INDX_S_PORT, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "S_PORTW", 0, { 2, INDX_S_PORTW, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "D_NUMBYTES", 0, { 0, INDX_D_NUMBYTES, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "D_NUMPOINTS", 0, { 0, INDX_D_NUMPTS, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,                  // 130
   "D_ADD_MEM", 0, { 3, INDX_D_ADD_MEM, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_ADP", 0, { 0, INDX_DG_ADP, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "D_AREA", 0, { 3, INDX_D_AREA, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "D_READ_MEM", 0, { 4, INDX_D_READ_MEM, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "D_LOAD_MEM", 0, { 4, INDX_D_LOAD_MEM, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "D_CAREA", 0, { 3, INDX_D_CAREA, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "D_CL", 0, { 0, INDX_D_CL, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "D_CLR", 0, { 1, INDX_D_CLR, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,                   // 140
   "D_CLR_ALL", 0, { 0, INDX_D_CLR_ALL, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "D_CRM", 0, { 0, INDX_D_CRM, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_DA", 0, { 0, INDX_DG_DA, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_DA", 0, { 1, INDX_DS_DA, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "D_LOAD_DAD", 0, { 1, INDX_D_LOAD_DAD, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,           // 150
   "DG_DM", 0, { 0, INDX_DG_DM, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_DT", 0, { 0, INDX_DG_DT, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_DT", 0, { 1, INDX_DS_DT, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_ERR", 0, { 0, INDX_DG_ERR, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_ET", 0, { 0, INDX_DG_ET, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_ET", 0, { 1, INDX_DS_ET, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,           // 160
   "DG_FREQ", 0, { 0, INDX_DG_FREQ, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_FREQ", 0, { 1, INDX_DS_FREQ, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_I", 0, { 0, INDX_DG_I, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_I", 0, { 1, INDX_DS_I, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_ID", 0, { 0, INDX_DG_ID, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_J", 0, { 0, INDX_DG_J, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_J", 0, { 1, INDX_DS_J, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,           // 170
   "DG_K", 0, { 0, INDX_DG_K, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_K", 0, { 1, INDX_DS_K, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,           // 170
   "DG_L", 0, { 0, INDX_DG_L, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_L", 0, { 1, INDX_DS_L, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "D_STORE_DAD", 0, { 1, INDX_D_STORE_DAD, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_MAX_MEM", 0, { 0, INDX_DG_MAX_MEM, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_MEM", 0, { 0, INDX_DG_MEM, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_MEM", 0, { 1, INDX_DS_MEM, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_MIN_ET", 0, { 0, INDX_DG_MIN_ET, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_PTIME", 0, { 0, INDX_DG_PTIME, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_PTIME", 0, { 1, INDX_DS_PTIME, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_STIME", 0, { 0, INDX_DG_STIME, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_STIME", 0, { 1, INDX_DS_STIME, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_FTIME", 0, { 0, INDX_DG_FTIME, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_PD", 0, { 0, INDX_DG_PD, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_PD", 0, { 1, INDX_DS_PD, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_PLSR", 0, { 0, INDX_DG_PLSR, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_PW", 0, { 0, INDX_DG_PW, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_PW", 0, { 1, INDX_DS_PW, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "D_RUN", 0, { 1, INDX_D_RUN, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "D_STOP", 0, { 1, INDX_D_STOP, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,           // 200
   "DG_SAME_ET", 0, { 0, INDX_DG_SAME_ET, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_SAME_ET", 0, { 1, INDX_DS_SAME_ET, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_SHUTTER", 0, { 1, INDX_DS_SHUTTER, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "D_SUB", 0, { 3, INDX_D_SUB, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "D_SUB_MEM", 0, { 3, INDX_D_SUB, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_SYNC", 0, { 0, INDX_DG_SYNC, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_SYNC", 0, { 1, INDX_DS_SYNC, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_VER", 0, { 0, INDX_DG_VER, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_ACTIVEX", 0, { 0, INDX_DG_ACTIVEX, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_ACTIVEX", 0, { 1, INDX_DS_ACTIVEX, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_ACTIVEY", 0, { 0, INDX_DG_ACTIVEY, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_ACTIVEY", 0, { 1, INDX_DS_ACTIVEY, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_DELTAX", 0, { 0, INDX_DG_DELTAX, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_DELTAX", 0, { 1, INDX_DS_DELTAX, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,           // 220
   "DG_DELTAY", 0, { 0, INDX_DG_DELTAY, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_DELTAY", 0, { 1, INDX_DS_DELTAY, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_ANTIBLOOM", 0, { 0, INDX_DG_ANTI_BLOOM, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_ANTIBLOOM", 0, { 1, INDX_DS_ANTI_BLOOM, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_H", 0, { 0, INDX_DG_H, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_H", 0, { 1, INDX_DS_H, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_OUTPUT_REG", 0, { 0, INDX_DG_OUTPUT_REG, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_OUTPUT_REG", 0, { 1, INDX_DS_OUTPUT_REG, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_SCANMODE", 0, { 0, INDX_DG_SCANMODE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,                    // 230
   "DS_SCANMODE", 0, { 1, INDX_DS_SCANMODE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_SHUTMODE", 0, { 0, INDX_DG_SHUTMODE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_SHUTMODE", 0, { 1, INDX_DS_SHUTMODE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_SCITC", 0, { 0, INDX_DG_SCITC, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_SCITC", 0, { 1, INDX_DS_SCITC, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_SCMP", 0, { 0, INDX_DG_SCMP, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_POINTMODE", 0, { 0, INDX_DG_SLCMODE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_POINTMODE", 0, { 1, INDX_DS_SLCMODE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_POINT", 0, { 0, INDX_DG_POINT, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,                    // 240
   "DS_POINT", 0, { 1, INDX_DS_POINT, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_POINTS", 0, { 0, INDX_DG_POINTS, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_POINTS", 0, { 1, INDX_DS_POINTS, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_REGIONS", 0, { 0, INDX_DG_REGIONS, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_REGIONS", 0, { 1, INDX_DS_REGIONS, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_REGION", 0, { 0, INDX_DG_REGION, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_REGION", 0, { 1, INDX_DS_REGION, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_REGSIZE", 0, { 0, INDX_DG_REGSIZE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_REGSIZE", 0, { 1, INDX_DS_REGSIZE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_REGET", 0, { 0, INDX_DG_REGET, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_REGET", 0, { 1, INDX_DS_REGET, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_TRACK", 0, { 0, INDX_DG_TRACK, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_TRACK", 0, { 1, INDX_DS_TRACK, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_TRACKS", 0, { 0, INDX_DG_TRACKS, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_TRACKS", 0, { 1, INDX_DS_TRACKS, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_TRKMODE", 0, { 0, INDX_DG_TRKMODE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_TRKMODE", 0, { 1, INDX_DS_TRKMODE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_WFTC", 0, { 0, INDX_DG_WFTC, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,                    // 250
   "DS_WFTC", 0, { 1, INDX_DS_WFTC, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_WFTO", 0, { 0, INDX_DG_WFTO, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_WFTO", 0, { 1, INDX_DS_WFTO, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_X0", 0, { 0, INDX_DG_X0, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_X0", 0, { 1, INDX_DS_X0, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_Y0", 0, { 0, INDX_DG_Y0, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DS_Y0", 0, { 1, INDX_DS_Y0, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "DG_OUTPIA", 0, { 0, INDX_DGOUTPIA, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "DS_OUTPIA", 0, { 1, INDX_DSOUTPIA, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "DG_INPIA", 0, { 0, INDX_DGINPIA, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "DG_PAUDIO", 0, { 0, INDX_DGPAUDIO, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "DS_PAUDIO", 0, { 1, INDX_DSPAUDIO, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "DG_PTRIGNUM", 0, { 0, INDX_DGPTRIGNUM, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "DS_PTRIGNUM", 0, { 1, INDX_DSPTRIGNUM, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "DG_PTRIGSRC", 0, { 0, INDX_DGPTRIGSRC, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "DS_PTRIGSRC", 0, { 1, INDX_DSPTRIGSRC, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "DG_PTRIGTRSH", 0, { 0, INDX_DGPTRIGTRSH, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "DS_PTRIGTRSH", 0, { 1, INDX_DSPTRIGTRSH, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "DG_PDELINC", 0, { 0, INDX_DGPDELINC, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "DS_PDELINC", 0, { 1, INDX_DSPDELINC, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "DG_PDELRANGE", 0, { 0, INDX_DGPDELRANGE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "DS_PDELRANGE", 0, { 1, INDX_DSPDELRANGE, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "DG_PIMODE", 0, { 0, INDX_DGPIMODE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "DS_PIMODE", 0, { 1, INDX_DSPIMODE, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "DG_STREAKMODE", 0, { 0, INDX_DGSTREAKMODE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "DS_STREAKMODE", 0, { 1, INDX_DSSTREAKMODE, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "DG_EXPOSEDROWS", 0, { 0, INDX_DGEXPOSEDROWS, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "DS_EXPOSEDEROWS", 0, { 1, INDX_DSEXPOSEDROWS, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "DG_PRETRIG_TRKS", 0, { 0, INDX_DGPRETRIGTRACKS, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "DS_PRETRIG_TRKS", 0, { 1, INDX_DSPRETRIGTRACKS, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "CREATE_CURVE", 0, { 4, INDX_CREATE_CURVE, INVALID_INDEX } },

/* record and playback functions */
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "MENU_REF", 0, { 1, INDX_MENU_REF, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "FORM_REF", 0, { 1, INDX_FORM_REF, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,                    // 260
   "FIELD_REF", 0, { 1, INDX_FIELD_REF, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "LEAVE_FORM", 0, { 0, INDX_LEAVE_FORM, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "LEAVE_MENU", 0, { 0, INDX_LEAVE_MENU, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "FOCUS_FIELD", 0, { 1, INDX_FOCUS_FIELD, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "ENTER_GRAPH", 0, { 0, INDX_ENTER_GRAPH, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "LEAVE_GRAPH", 0, { 0, INDX_LEAVE_GRAPH, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "HELP", 0, { 1, INDX_HELP, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "GO_LIVE", 0, { 0, INDX_GO_LIVE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "STOP_LIVE", 0, { 0, INDX_STOP_LIVE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,                    // 270
   "ZOOM", 0, { 4, INDX_ZOOM, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "RESTORE_ZOOM", 0, { 0, INDX_RESTORE_ZOOM, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "AUTO_SCALE", 0, { 0, INDX_AUTO_SCALE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "SCALE_X", 0, { 0, INDX_SCALEX, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "SCALE_Y", 0, { 0, INDX_SCALEY, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "SCALE_Z", 0, { 0, INDX_SCALEZ, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "SELECT_WINDOW", 0, { 1, INDX_SELECT_WINDOW, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "SET_PEAK_THRESHOLD", 0, { 3, INDX_SET_THRESHOLD, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "DRAW_PEAKS", 0, { 0, INDX_DRAW_PEAKS, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "ADD_KNOT", 0, { 2, INDX_ADD_KNOT, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "REPLOT_WINDOW", 0, { 0, INDX_REPLOT_WINDOW, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "REPLOT_SCREEN", 0, { 0, INDX_REPLOT_SCREEN, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "MOVE_CURSOR", 0, { 2, INDX_MOVE_CURSOR, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "X_EXPAND", 0, { 0, INDX_EXPAND_X, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "Y_EXPAND", 0, { 0, INDX_EXPAND_Y, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "X_CONTRACT", 0, { 0, INDX_CONTRACT_X, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "Y_CONTRACT", 0, { 0, INDX_CONTRACT_Y, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,           // 280
   "G_ACTIVE_PLOT", 0, { 0, INDX_G_ACTIVE_PLOT, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "S_ACTIVE_PLOT", 0, { 1, INDX_S_ACTIVE_PLOT, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "EXPAND_TAGGED", 0, { 0, INDX_EXPAND_TAGGED, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "RESTORE_EXPAND", 0, { 0, INDX_RESTORE_EXPAND, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "TAG_CURVE", 0, { 0, INDX_TAG_CURVE, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
   "UNTAG_CURVE", 0, { 0, INDX_UNTAG_CURVE, INVALID_INDEX } },

{ CLASS_STRING, TYPE_STRING, SYMATTR_NONE,
   "DEF_NAME", 0, {FNAME_LENGTH, 0L} },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_COOL", 0, { 0, INDX_DG_COOL, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,                   // 288
   "DS_COOL", 0, { 1, INDX_DS_COOL, INVALID_INDEX } },
{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
   "DG_ACTIVE", 0, { 0, INDX_DG_ACTIVE, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "SPEC_CMD", 0, { 1, INDX_SPEC_CMD, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "SPEC_GETS", 0, { 2, INDX_SPEC_GETS, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "SPEC_RESET", 0, { 0, INDX_SPEC_RESET, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "SPEC_SELECT", 0, { 1, INDX_SPEC_SELECT, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "SPEC_OFFSET", 0, { 2, INDX_SPEC_OFFSET, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "SPEC_GO", 0, { 0, INDX_SPEC_GO, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "SPEC_WLEN", 0, { 1, INDX_SPEC_WLEN, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "SPEC_GRATING", 0, { 1, INDX_SPEC_GRATING, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "SPEC_STORE", 0, { 0, INDX_SPEC_STORE, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "SPEC_S_DISP", 0, { 1, INDX_SPEC_S_DISP, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "DOSCMD", 0, { 1, INDX_DOSCMD, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "STOF", 0, { 1, INDX_STOF, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "FTOS", 0, { 1, INDX_FTOS, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "GCMD_PROMPT", 0, { 0, INDX_GCMD_PROMPT, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "SCMD_PROMPT", 0, { 1, INDX_SCMD_PROMPT, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "CMD_PROMPT", 0, { 1, INDX_SCMD_PROMPT, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "LOAD_LAMPFILE", 0, { 1, INDX_LOADLAMPFILE, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "SAVE_LAMPFILE", 0, { 1, INDX_SAVELAMPFILE, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "ADD_YCALPAIR", 0, { 2, INDX_ADDYCALIBPAIR, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "DEL_YCALPAIR", 0, { 1, INDX_DELYCALIBPAIR, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "DEL_LAMPDATA", 0, { 0, INDX_DELETELAMPDATA, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "GEN_CORREXSET", 0, { 2, INDX_GENCORREXSET, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "SET_LIVEFILTER", 0, { 2, INDX_SETFILTER, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "WAIT", 0, { 1, INDX_MACWAIT, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "COM_INIT", 0, { 5, INDX_MACCOMINIT, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "COM_STATUS", 0, { 1, INDX_MACCOMSTAT, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "COM_OUT", 0, { 2, INDX_MACCOMOUT, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "COM_IN", 0, { 2, INDX_MACCOMIN, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "READ_MOUSE", 0, { 5, INDX_MACRDMOUSE, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "PAUSE_RUN", 0, { 0, INDX_MACPAUSEL, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "FREE_RUN", 0, { 0, INDX_MACFREERL, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "NOW", 0, { 0, INDX_SYSTIME, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_RETURNS_VALUE,
 "G_CALIB", 0, { 5, INDX_GETCAL, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,
 "S_CALIB", 0, { 6, INDX_SETCAL, INVALID_INDEX } },

{ CLASS_EXECUTABLE, TYPE_PROCEDURE, SYMATTR_NONE,                    // 100
 "G_PLOT_STYLE", 0, { 20, INDX_G_PLOT_STYLE, INVALID_INDEX } },

#ifdef NEWPLOT
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "PXMIN", 0, (int)PLOT_XMIN  },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "PXMAX", 0, (int)PLOT_XMAX  },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "PYMIN", 0, (int)PLOT_YMIN  },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "PYMAX", 0, (int)PLOT_YMAX  },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "PZMIN", 0, (int)PLOT_ZMIN  },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "PZMAX", 0, (int)PLOT_ZMAX  },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "PXUNIT",0, (int)PLOT_XUNIT },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "PYUNIT",0, (int)PLOT_YUNIT },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "ZUNIT", 0, (int)PLOT_ZUNIT },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "TITLE", 0, (int)PLOT_TITLE },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "XLABL", 0, (int)PLOT_XLABL },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "YLABL", 0, (int)PLOT_YLABL },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "ZLABL", 0, (int)PLOT_ZLABL },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "ZLABL", 0, (int)PLOT_ZLABL },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "ZXPCT", 0, (int)PLOT_ZXPCT },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "ZYPCT", 0, (int)PLOT_ZYPCT },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "LINSTY",0, (int)PLOT_LNSTY },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "AUTOX", 0, (int)PLOT_AUTOX },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "AUTOY", 0, (int)PLOT_AUTOY },
{ CLASS_SCALAR, TYPE_INTEGER, SYMATTR_CONSTANT, "AUTOZ", 0, (int)PLOT_AUTOZ },
#endif

} ;

int main( int argc, char *argv[])
{
   PCHAR FileName;
   FILE *hFile;
   CHAR TempStr[FTIDLEN];
   unsigned int DeclNum =
                   sizeof( PreDefSymbols ) / sizeof( PreDefSymbols[ 0 ] ) ;

   if (argc > 1)
      FileName = argv[1];
   else
      {
      FileName = malloc( FNAME_LENGTH );
      printf( "File name? " );
      scanf( "%s", FileName );
      printf( "\n" );
      }

   hFile = fopen( FileName, "wb" );
   if (hFile == NULL)
      {
      printf( "Can't open file %s\n", FileName );
      return TRUE;
      }

   strcpy( TempStr, fidMacroOMA4 );
   if (fwrite( TempStr, 1, FTIDLEN, hFile ) != FTIDLEN)
      {
      printf( "Write error with file %s\n", FileName );
      fclose( hFile );
      return TRUE;
      }

   if (fwrite( Version, 1, VERLEN, hFile ) != VERLEN)
      {
      printf( "Write error with file %s\n", FileName );
      fclose( hFile );
      return TRUE;
      }

   if (fwrite( &DeclNum, sizeof(SHORT), 1, hFile ) != 1)
      {
      printf( "Write error with file %s\n", FileName );
      fclose( hFile );
      return TRUE;
      }

   if (fwrite( PreDefSymbols, sizeof(DECLARATION), DeclNum, hFile ) != DeclNum)
      {
      printf( "Write error with file %s\n", FileName );
      fclose( hFile );
      return TRUE;
      }

   fclose( hFile );

   return FALSE;
}
