;/**************************************************************************/
;/*									   */
;/* PCSYS.INC                                                              */    
;/*              PC Hardware Constants                                     */
;/*                                                                        */
;/**************************************************************************/

ADDRESS_PORT_8042       EQU     070H
DATA_PORT_8042          EQU     071H
; 8042 internal addresses
EXPANDED_MEM_1_LOW      EQU     017H
EXPANDED_MEM_1_HIGH     EQU     018H 
EXPANDED_MEM_2_LOW      EQU     030H
EXPANDED_MEM_2_HIGH     EQU     031H
CHECKSUM_LOW            EQU     02FH
CHECKSUM_HIGH           EQU     02EH

