//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by BASEDISP.RC
//
#define IDR_MAINFRAME                   2
#define IDR_APPTYPE                     3
#define IDS_ERRFILEOPEN                 3
#define IDS_ERRFILESAVE                 4
#define IDC_BTNZFRM                     5
#define IDD_ABOUTBOX                    100
#define IDD_DLGBAR1                     102
#define IDB_BRITE                       112
#define IDB_CONT                        115
#define IDB_ZOOM                        116
#define IDB_SLIDE                       122
#define IDB_HRIGHT                      123
#define IDB_HLEFT                       124
#define IDB_VUP                         125
#define IDB_VDOWN                       126
#define IDB_ZFRMUP                      133
#define IDB_ZFRMDN                      134
#define IDD_RECTINFO                    136
#define IDB_SLIDEHDL                    137
#define IDB_SLIDEMSK                    138
#define IDC_BRITE                       1000
#define IDC_CONT                        1002
#define IDC_FRM_BRITE                   1010
#define IDC_FRM_CONT                    1015
#define IDC_BTNZOOM                     1030
#define IDC_BTNVFLIP                    1031
#define IDC_BTNHFLIP                    1032
#define IDP_OLE_INIT_FAILED             1033
#define IDC_DMAX                        1034
#define IDC_DMIN                        1035
#define IDC_CK_SETSCROLL                1051
#define IDC_BTNCONT                     1058
#define IDC_BTNBRITE                    1059
#define IDC_SRC_TLX                     1059
#define IDC_SRC_TLY                     1060
#define IDC_SRC_BRX                     1061
#define IDC_SRC_BRY                     1062
#define IDC_SRC_SIZX                    1063
#define IDC_SRC_SIZY                    1064
#define IDC_CLR_TLX                     1065
#define IDC_CLR_TLY                     1066
#define IDC_CLR_BRX                     1067
#define IDC_CLR_BRY                     1068
#define IDC_CLR_SIZX                    1069
#define IDC_CLR_SIZY                    1070
#define IDC_PANEL3D2                    1071
#define IDS_AUTOSCALE                   32767
#define IDS_AUTOAUTO                    32768
#define ID_INDICATOR_MOUSEX             32769
#define ID_INDICATOR_MOUSEY             32770
#define ID_INDICATOR_MOUSEVAL           32771
#define ID_IMAGE_FLIP                   32773
#define ID_IMAGE_FLIPHORIZONTAL         32774
#define ID_IMAGE_REPEATAUTOSCALE        32775
#define ID_VIEW_CONTROLS                32780
#define IDM_PROC                        32786
#define IDM_PROC1                       32787
#define IDM_PROC2                       32788
#define IDM_VIEW_INFO                   32789
#define ID_OPT_DELBTN                   32790
#define ID_AUTOSIZE_WINDOW              32791
#define ID_OPT_1TO1                     32792

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           500
#endif
#endif
