// stdafx.h : include file for standard system include files,
//  or project specific include files that are used frequently, but
//      are changed infrequently
//
//////////////////////////////////////////////////////////////////////////
//   This revision:  $Revision:   1.1  $
//   Last check-in   $Date:   29 Sep 1995 20:57:02  $
//   Last changes by $Author:   MLM  $
//   Changes:
//   $Log:   S:/SOFTWARE/WINX20/BASEDISP/SOURCE/STDAFX.H_V  $
// 
//    Rev 1.1   29 Sep 1995 20:57:02   MLM
// Add PVCS info tags
//  
//////////////////////////////////////////////////////////////////////////

#include <afxwin.h>     // MFC core and standard components
#include <afxext.h>     // MFC extensions (including VB)
#include <afxole.h>     // MFC OLE 2.0 support
