/* -----------------------------------------------------------------------
/  runsetup.h
/
/  Copyright (c) 1989,  EG&G Instruments Inc.
/
/  Written by: RAC      Version 1.0  May 5, 1991
/
/  $Header: /OMA4000/Include/RUNSETUP.H 1     6/18/99 1:53a Maynard $
 * 
 *    Rev 1.0   06 May 1991 11:37:32   cole
 * Initial revision.
/
/ -------------------------------------------------------------------------
*/
  
#ifndef RUNSETUP_INCLUDED
#define RUNSETUP_INCLUDED

// put & DA_Form into FormTable[]
void registerDA_Form(void);

#endif  // RUNSETUP_INCLUDED
