@cls
@ECHO  ********  OMA Controller Diagnostic program Help utility  *********
@ECHO.
@ECHO          - There are several diagnostic programs on this
@ECHO            disk.  They are used to check the functionality
@ECHO            of the OMAIV system.  Each program will size your
@ECHO            computer's memory configuration and fit the OMA
@ECHO            Controller board where appropriate.  
@ECHO          - This disk contains the following diagnostics:
@ECHO              1. CKMEM       -- This program will check the host
@ECHO                                computer's access to memory.
@ECHO              2. CKDAC       -- This program will check the 
@ECHO                                functionality of the Data Acquisition
@ECHO                                Controller.
@ECHO              3. LOOPBACK    -- This program will verify the OMA 
@ECHO                                Controller and the Detector Controller
@ECHO                                as a system.
@ECHO              4. CKPIA       -- This program is used to check the 
@ECHO                                Parallel Input/output Adaptor, Trigger
@ECHO                                Outputs and Shutter controls. 
@ECHO          - To obtain the command line syntax for any program,
@ECHO            just type the program's name followed by the Enter key.
